import Head from "next/head";
import styled from "@emotion/styled";
import Link from "next/link";

const Wrapper = styled.div`
  width: 1200px;
  margin: 0 auto;
  padding: 100px 50px 200px 50px;
  /* text-align: center; */
`;
const Title = styled.h1`
  margin-bottom: 40px;
  font-size: 48px;
`;
const SmallTitle = styled.h2`
  font-size: 24px;
  margin-bottom: 20px;
`;
const Button = styled.button`
  width: 150px;
  height: 50px;
  margin-top: 50px;
  border: none;
  background-color: #ffd600;
  font-size: 16px;
  font-weight: bold;
  cursor: pointer;
  :hover {
    background-color: black;
    color: white;
  }
`;

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Ssummer store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Title>Welcome to Ssummer Store</Title>
        <SmallTitle>
          There&apos;re plenty of wonderful second hand things to get
        </SmallTitle>
        <SmallTitle>You can also sell them</SmallTitle>
        <SmallTitle>Do not hesitate!</SmallTitle>
        <Link href="/login">
          <Button>Join us now!</Button>
        </Link>
      </Wrapper>
    </>
  );
}
